apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverjs
  namespace: templateapp
spec:
  selector:
    matchLabels:
      app: serverjs
  template:
    metadata:
      labels:
        app: serverjs
    spec:
      containers:
      - name: serverjs
        image: xitric/trace-serverjs:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        # Inject the IP of the node to the container, so that it can send trace
        # data to the local DaemonSet
        env:
        - name: OTEL_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
---
apiVersion: v1
kind: Service
metadata:
  name: serverjs-service
  namespace: templateapp
spec:
  selector:
    app: serverjs
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
