apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-config
spec:
  strategy: production
  collector:
    maxReplicas: 3
    resources:
      limits:
        cpu: 500m
        memory: 256Mi