apiVersion: v1
kind: Service
metadata:
  name: jaeger-ui-service
  namespace: templateapp
spec:
  selector:
    app: jaeger
  type: LoadBalancer
  ports:
  - port: 16686
    targetPort: 16686
    nodePort: 30001
