version: "3.5"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.21
    container_name: jaeger
    restart: on-failure
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      jaeger_network:
        ipv4_address: 172.200.0.2
  
  server:
    image: node:latest
    container_name: server
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./server:/home/node/app
    expose:
      - 3000
    ports:
      - 80:3000
    command: "npm start"
    networks:
      jaeger_network:
        ipv4_address: 172.200.0.3
  
  service_hello:
    image: node:latest
    container_name: service_hello
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./service_hello:/home/node/app
    command: "npm start"
    networks:
      jaeger_network:
        ipv4_address: 172.200.0.4
  
  service_info:
    image: node:latest
    container_name: service_info
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./service_info:/home/node/app
    command: "npm start"
    networks:
      jaeger_network:
        ipv4_address: 172.200.0.5

networks:
  jaeger_network:
    name: jaeger_network
    ipam:
      config:
        - subnet: 172.200.0.0/24
