apiVersion: apps/v1
kind: Deployment
metadata:
  name: info
  namespace: templateapp
spec:
  selector:
    matchLabels:
      app: info
  template:
    metadata:
      labels:
        app: info
    spec:
      containers:
      - name: info
        image: xitric/trace-info:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: info-service
  namespace: templateapp
spec:
  selector:
    app: info
  ports:
  - port: 80
    targetPort: 3000
