apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: templateapp
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: xitric/trace-server:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
      - name: agent
        image: jaegertracing/jaeger-opentelemetry-agent:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: templateapp
spec:
  selector:
    app: server
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
